# Generated by Django 5.1.1 on 2024-09-20 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Subscription name')),
                ('subscription_type', models.CharField(choices=[('general', 'General'), ('group', 'Group Classes'), ('personal', 'Personal Training'), ('massage', 'Massage')], max_length=15, verbose_name='Subscription type')),
                ('validity_period', models.IntegerField(verbose_name='Validity period')),
                ('available_number_of_visits', models.IntegerField(verbose_name='Available number of visits')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscription', verbose_name='Subscription')),
            ],
        ),
    ]
