# Generated by Django 5.1.1 on 2024-09-23 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_time', models.DateTimeField(auto_now_add=True, verbose_name='Attendance Datetime')),
                ('user_subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.usersubscription', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
            },
        ),
        migrations.CreateModel(
            name='AttendanceTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.attendance', verbose_name='Attendance')),
            ],
            options={
                'verbose_name': 'Attendance Training',
                'verbose_name_plural': 'Attendance Trainings',
            },
        ),
    ]
