# Generated by Django 5.1.1 on 2024-09-23 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancetraining',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainings.training', verbose_name='Training'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancetraining',
            unique_together={('attendance', 'training')},
        ),
    ]
