# Generated by Django 5.1.1 on 2024-09-23 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0002_initial'),
        ('trainings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='trainer',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Trainer'),
        ),
        migrations.AddField(
            model_name='traininguser',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainings.training', verbose_name='Training'),
        ),
        migrations.AddField(
            model_name='traininguser',
            name='user_subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.usersubscription', verbose_name='Participant'),
        ),
        migrations.AddConstraint(
            model_name='traininguser',
            constraint=models.UniqueConstraint(fields=('user_subscription', 'training'), name='unique_training_user'),
        ),
    ]
